title: WebDevJosue
email: WebDev.Josue@gmail.com
description: Portfolio website showcasing web development projects and skills
baseurl: ""
url: "https://webdevjosue.github.io"
github_username: webdevjosue

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
theme: minima

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
