title: Josue Zazueta Portfolio
email: WebDev.Josue@gmail.com
description: Web Developer Portfolio
baseurl: ""
url: "https://webdevjosue.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# SEO settings
kramdown:
  syntax_highlighter_opts:
    disable: true

defaults:
  - scope:
      path: "" # all files
    values:
      sitemap: false
      noindex: true

# Exclude files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
